### ISSUE TITLE
RunDeck 検証

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#31]
## RunDeck

https://docs.rundeck.com/docs/manual/01-introduction.html

* Jenkins のようにジョブが実行できる
* データを MySQL のような RDB に保持できる
* ジョブの実行ログなどを S3 などに保持できる
* OAuth2 認証がめんどくさそうで、既に開発止まってる oauth2_proxy が必要？
  * https://qiita.com/minamijoyo/items/52041ff8628263355810
  * https://github.com/rundeck/rundeck/issues/5656
  * https://docs.rundeck.com/docs/administration/security/authentication.html#preauthenticated-mode-using-headers

https://docs.rundeck.com/docs/administration/overview/system-architecture.html

> Rundeck stores job definitions and execution history in a relational database.
> Output from command and job executions is saved on disk but can be forwarded to remote stores like S3 or Logstash.

## Terraform

https://www.terraform.io/docs/providers/rundeck/index.html

Terraform で管理するとして、CircleCI から Terraform 実行するとかしたら、 CircleCI から API 叩けるように穴を空ける必要がある

---

* 細かく権限絞れるので、 read 権限とジョブ実行権限のみ付与する
* Terraform で Project と job の管理をする

というのも一つの手かもしれない。それでユーザーが幸せになれるかは考えないといけない

---

- [x] 定期実行 https://docs.rundeck.com/docs/manual/creating-jobs.html#scheduled-jobs
- [x] パラメータ https://docs.rundeck.com/docs/manual/job-options.html

## ローカルで動かす

```yaml
---
# docker run --name rundeck -p 4440:4440 -v rundeck-data:/home/rundeck/server/data rundeck/rundeck:3.1.2
version: "3"
services:
  rundeck:
    image: rundeck/rundeck:3.1.2
    ports:
    - "4440:4440"
    volumes:
    - "rundeck-data:/home/rundeck/server/data"
volumes:
  rundeck-data:
```
