### ISSUE TITLE
local で Drone の Kubernetes Runner を動かす

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#36]
* MySQL
* Drone Server - GitHub
* Drone Runner

## ngrok

https://ngrok.com/

GitHub から WebHook を受ける必要があるので、 ngrok を使う。
一時的に外部に Drone を公開することになるので、何があっても自分は責任を取らない。

自分以外がログインできないようにユーザーを制限しておく。

https://docs.drone.io/installation/security/registration/

```
$ brew install cask ngrok
```

## k8s

kind で動かす

```
$ kind create cluster --name drone
$ kubectl create ns drone
$ kubens drone
```

## MySQL

Helm で動かす

https://github.com/helm/charts/tree/master/stable/mysql

```
$ helm install drone \
  --set mysqlRootPassword=password,mysqlDatabase=drone \
    stable/mysql
```

```
$ kubectl exec -ti drone-mysql-??? mysql -- -u root -p drone
```

## Drone Server

* https://docs.drone.io/installation/providers/github/
* https://docs.drone.io/installation/reference/

GitHub OAuth App を作る。 URL は http://example.com とでもしておいて後で変更する。

Drone Server も k8s で Deployment として動かす。
k8s の Service で公開する。
ソースコードを確認したところ、 Web UI 及び WebHook を受けるポートと、 Runner と RPC で通信するポートは同じである。

https://github.com/drone/drone/blob/v1.6.5/cmd/drone-server/inject_server.go#L62-L72

path によって API や RPC を区別しているのがわかる。

以下の情報を secret として Drone Server に渡す

* DRONE_GITHUB_CLIENT_ID
* DRONE_GITHUB_CLIENT_SECRET
* DRONE_DATABASE_DATASOURCE
* DRONE_RPC_SECRET

ファイルを作る際は vim などのエディタで書くと末尾に改行が入ってしまうことがあるので

```
$ echo -n '***' > secrets/drone-github-cliet-id
```

のように `echo -n` を使うのが無難

```
secrets/
  drone-github-cliet-id
  drone-github-client-secret
  drone-datasource
  drone-rpc-secret
```

```
$ kubectl create secret generic drone-server \
  --from-file=secrets/drone-github-client-id \
  --from-file=secrets/drone-github-client-secret \
  --from-file=secrets/drone-datasource

$ kubectl create secret generic drone-server-rpc \
  --from-file=secrets/drone-rpc-secret
```

https://docs.drone.io/installation/security/registration/

server.yaml

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
spec:
  selector:
    app.kubernetes.io/name: drone-server
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 80
  - name: https
    protocol: TCP
    port: 4443
    targetPort: 443
  - name: rpc
    protocol: TCP
    port: 3000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-server
    spec:
      containers:
      - name: runner
        image: drone/drone:1.6.5
        env:
        - name: DRONE_DATABASE_DRIVER
          value: mysql
        - name: DRONE_SERVER_PROTO
          value: http
        - name: DRONE_SERVER_HOST
          value: http://localhost
        - name: DRONE_USER_FILTER
          value: suzuki-shunsuke
        - name: DRONE_DATABASE_DATASOURCE
          valueFrom:
            secretKeyRef:
              name: drone-mysql
              key: datasource
        - name: DRONE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth-app
              key: client_id
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth-app
              key: client_secret
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-rpc-secret
              key: rpc_secret
```

## Drone Runner

* https://kube-runner.docs.drone.io/installation/installation/
* https://kube-runner.docs.drone.io/installation/reference/

rbac.yaml

公式のサンプルだと `default` namespace にハードコードされていたので、それを外している。

```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io
```

runner.yaml

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: drone-runner
spec:
  selector:
    app.kubernetes.io/name: drone-runner
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  labels:
    app.kubernetes.io/name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: drone-server:3000
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-rpc-secret
              key: rpc_secret
```

## Ngrok で公開する

```
$ kubectl port-forward svc/drone-server 4000:4000
```

```
$ ngrok http 4000
```

その後 GitHub OAuth App の `Homepage URL` と `Authorization callback URL` を修正する。
callback URL のパスは `/login`

その後ブラウザからアクセスしてみる。
