### ISSUE TITLE
"Understanding resource limits in kubernetes: memory" を読んで

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#38]
https://medium.com/@betz.mark/understanding-resource-limits-in-kubernetes-memory-6b41e9a955f9

resource limit と request

* limit: 起動中の Pod の使用リソースを制限
  * k8s -> コンテナランタイム(Docker) -> Linux cgroup というふうに設定がされていく
* request: kubelet が Pod を Node にスケジューリングする際に影響
  * limit と違い、コンテナ作成時のコンテナの設定には影響しない
  * request を設定していないと、デフォルトで limit と同じになる
* request が大きすぎると Pod をスケジューリングできなくなる(pending)
* request が小さすぎると memory の場合 OOM が起こったりする

設定例

```yaml
resources:
  requests:
    cpu: 50m # 5% の cpu time
    memory: 50Mi # 50MiB のメモリが必要
  limits:
    cpu: 100m
    memory: 100Mi
```

cgroup

関連したプロパティをグルーピングし、グループに階層構造を持たせられる
