### ISSUE TITLE
CircleCI の workspace

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#40]
* https://circleci.com/docs/2.0/configuration-reference/#attach_workspace

```yaml
- persist_to_workspace:
    root: /tmp/dir
    paths:
      - foo/bar
      - baz
- attach_workspace:
    at: /tmp/workspace
```

## persist_to_workspace

* root: 絶対パスか、 `working_directory` からの相対パス
* paths: workspace root からの相対パス。 workspace root 自体にはするべきでない。 shared workspace に追加される

## attach_workspace

* at: workspace をアタッチするコンテナのパス。 workspace のすべてのファイルが at にアタッチされる

## Example

* リポジトリを `<working_directory>/src` にチェックアウトする
* asset を `<working_directory>/changed`, `<working_directory>/bin` に置く
