### ISSUE TITLE
Argo Workflow v2.7.7 検証

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#43]
https://github.com/suzuki-shunsuke/issue/issues/34

https://argoproj.github.io/docs/argo/getting-started.html

```
$ minikube start
$ kubectl create namespace argo
$ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.7.7/manifests/install.yaml
$ kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
$ argo submit --watch https://raw.githubusercontent.com/argoproj/argo/v2.7.7/examples/hello-world.yaml
```

## Artifacts

```
$ helm install argo-artifacts stable/minio \
  --set service.type=LoadBalancer \
  --set defaultBucket.enabled=true \
  --set defaultBucket.name=my-bucket \
  --set persistence.enabled=false \
  --set fullnameOverride=argo-artifacts
```

<details>

```
NAME: argo-artifacts
LAST DEPLOYED: Sat May  9 19:36:21 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Minio can be accessed via port 9000 on an external IP address. Get the service external IP address by:
kubectl get svc --namespace default -l app=argo-artifacts

Note that the public IP may take a couple of minutes to be available.

You can now access Minio server on http://<External-IP>:9000. Follow the below steps to connect to Minio server with mc client:

  1. Download the Minio mc client - https://docs.minio.io/docs/minio-client-quickstart-guide

  2. mc config host add argo-artifacts-local http://<External-IP>:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY S3v4

  3. mc ls argo-artifacts-local

Alternately, you can use your browser or the Minio SDK to access the server - https://docs.minio.io/categories/17
```

</details>

```
$ minikube service --url argo-artifacts
http://192.168.64.7:31412
```

ブラウザから minio にアクセス

bucket `my-bucket` はつくられているはず

Artifacts を使うように workflow controller の設定(configmap)を更新

```
$ kubectl edit cm -n argo workflow-controller-configmap
```

<details>

```yaml
data:
  config: |
    artifactRepository: |
      s3:
        bucket: my-bucket
        endpoint: argo-artifacts.default:9000
        insecure: true
        # accessKeySecret and secretKeySecret are secret selectors.
        # It references the k8s secret named 'argo-artifacts'
        # which was created during the minio helm install. The keys,
        # 'accesskey' and 'secretkey', inside that secret are where the
        # actual minio credentials are stored.
        accessKeySecret:
          name: argo-artifacts
          key: accesskey
        secretKeySecret:
          name: argo-artifacts
          key: secretkey
```

</details>

## Argo にブラウザからアクセス

```
$ kubectl -n argo port-forward deployment/argo-server 2746:2746
```

http://localhost:2746

## Artifacts を使ったサンプルを動かす

```
$ argo submit https://raw.githubusercontent.com/argoproj/argo/v2.7.7/examples/artifact-passing.yaml
```

失敗する

```
(⎈ |minikube:default)❯ argo get artifact-passing-brdvw
Name:                artifact-passing-brdvw
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'artifact-passing-brdvw[0].generate-artifact' errored
Created:             Sat May 09 19:49:17 +0900 (39 seconds ago)
Started:             Sat May 09 19:49:17 +0900 (39 seconds ago)
Finished:            Sat May 09 19:49:17 +0900 (39 seconds ago)
Duration:            0 seconds

STEP                                          PODNAME                            DURATION  MESSAGE
 ✖ artifact-passing-brdvw (artifact-example)                                               child 'artifact-passing-brdvw[0].generate-artifact' errored
 └---⚠ generate-artifact (whalesay)           artifact-passing-brdvw-1514565897  0s        controller is not configured with a default archive location
```

https://github.com/argoproj/argo/issues/671#issuecomment-356729734

Artifact Repository が設定されていない？

configmap を更新したあとに workflow-controller restart する必要があるのでは？

```
$ (⎈ |minikube:default)❯ kubectl -n argo rollout restart deploy/workflow-controller
deployment.apps/workflow-controller restarted
```

失敗した。同じエラー。

> controller is not configured with a default archive location

archive だから artifact じゃなくて https://argoproj.github.io/docs/argo/workflow-archive.html
なのでは？

* https://github.com/argoproj/argo/blob/v2.7.7/examples/archive-location.yaml
* https://github.com/argoproj/argo/blob/v2.7.7/manifests/quick-start-postgres.yaml

## install.yaml の代わりに quick-start-postgres.yaml を使ってみる

いったん cluster 作り直す

```
$ minikube stop
$ minikube delete
$ minikube start
```

```
$ kubectl create namespace argo
$ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.7.7/manifests/quick-start-postgres.yaml
$ kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
```

```
$ kubectl -n argo port-forward deployment/argo-server 2746:2746
```

```
$ argo submit --watch https://raw.githubusercontent.com/argoproj/argo/v2.7.7/examples/hello-world.yaml
```

pending のまま動かない

https://raw.githubusercontent.com/argoproj/argo/v2.7.7/examples/hello-world.yaml

見る限り ClusterRole とか作ってないから同じ namespace じゃないとだめなのでは？

https://raw.githubusercontent.com/argoproj/argo/v2.7.7/manifests/install.yaml

から ConfigMap workflow-controller-configmap だけ消して apply してみる

```
$ wget https://raw.githubusercontent.com/argoproj/argo/v2.7.7/manifests/install.yaml
$ vi install.yaml
```

<details>

```yaml
# This is an auto-generated file. DO NOT EDIT
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronworkflows.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: CronWorkflow
    plural: cronworkflows
    shortNames:
    - cronwf
    - cwf
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Status of the workflow
    name: Status
    type: string
  - JSONPath: .status.startedAt
    description: When the workflow was started
    format: date-time
    name: Age
    type: date
  group: argoproj.io
  names:
    kind: Workflow
    plural: workflows
    shortNames:
    - wf
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflowtemplates.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: WorkflowTemplate
    plural: workflowtemplates
    shortNames:
    - wftmpl
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: argo-aggregate-to-admin
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: argo-aggregate-to-edit
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: argo-aggregate-to-view
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  - workflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-server-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  - cronworkflows
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-role
subjects:
- kind: ServiceAccount
  name: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: argo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-server
spec:
  ports:
  - port: 2746
    targetPort: 2746
  selector:
    app: argo-server
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-controller-metrics
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: workflow-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - args:
        - server
        image: argoproj/argocli:v2.7.7
        name: argo-server
        ports:
        - containerPort: 2746
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
      serviceAccountName: argo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v2.7.7
        command:
        - workflow-controller
        image: argoproj/workflow-controller:v2.7.7
        name: workflow-controller
      serviceAccountName: argo
```

</details>

```
$ kubectl apply -n argo -f install.yaml
```

```
$ argo submit --watch https://raw.githubusercontent.com/argoproj/argo/v2.7.7/examples/hello-world.yaml
```

動かない。 restart してみる。

動かないというか pending になっている。 STATUS は Running だが、 Web UI で PHASE が pending になっている。

```
(⎈ |minikube:default)❯ argo list
NAME                STATUS    AGE   DURATION   PRIORITY
hello-world-6jr46   Running   1m    1m         0
hello-world-fbzhw   Running   7m    7m         0
hello-world-fkdgp   Running   8m    8m         0
hello-world-dj2p7   Running   22m   9m         0
```

`--namespaced` 指定しているから同じ namespace じゃないと動かなさそう

https://argoproj.github.io/docs/argo/managed-namespace.html
https://github.com/argoproj/argo/blob/v2.7.7/manifests/quick-start-postgres.yaml#L405
