### ISSUE TITLE
Tekton を試す

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#48]
https://tekton.dev/docs/getting-started/

```
$ kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
```

PV が必要らしい

https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/

```
(⎈ |minikube:default)❯ kubectl get pv
No resources found in default namespace.

(⎈ |minikube:default)❯ kubectl get storageclasses
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  6m33s
```

pv.yaml

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
```

```
$ kubectl apply -f pv.yaml
$ kubectl get pv
NAME     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
pv0001   5Gi        RWO            Retain           Available                                   7m20s
```

```
$ brew tap tektoncd/tools
$ brew install tektoncd/tools/tektoncd-cli
```

Dashboard のインストール

```
$ kubectl apply --filename https://github.com/tektoncd/dashboard/releases/latest/download/tekton-dashboard-release.yaml
```
