### ISSUE TITLE
vim-terraform が動かない(読み込まれてない?)

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#5]
https://github.com/hashivim/vim-terraform

* ファイルを開いてもシンタックスハイライトが効かない
* ファイルを保存しても整形されない
* `:TerraformFmt` を実行すると正常になる。シンタックスハイライトも効くし、ファイルを保存すると整形されるようになる

https://github.com/Shougo/dein.vim でインストールしている

```vim
let g:terraform_fmt_on_save = 1
```

```toml
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['hcl', 'tf']
```
