### ISSUE TITLE
Argo Rollouts v0.8.2 を試す

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#50]
https://argoproj.github.io/argo-rollouts/getting-started/

```
$ minikube start
$ kubectl create namespace argo-rollouts
$ kubectl apply -n argo-rollouts -f https://raw.githubusercontent.com/argoproj/argo-rollouts/stable/manifests/install.yaml
$ kubectl apply -f rollout.yaml
$ kubectl get rollout
```

rollout.yaml

<details>

```yaml
apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
# ----- Everything below this comment is the same as a deployment -----
metadata:
  name: example-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  # ----- Everything above this comment are the same as a deployment -----
    canary: # A new field that used to provide configurable options for a Canary strategy
      steps:
      - setWeight: 20
      - pause: {}
```

</details>

```
$ kubectl patch rollout example-rollout --type merge -p '{"spec": {"template": { "spec": { "containers": [{"name": "nginx","image": "nginx:1.15.5"}]}}}}'
```

```
$ kb get rollout
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE
example-rollout   5         5         1            5

$ kb get replicaset
NAME                         DESIRED   CURRENT   READY   AGE
example-rollout-66767759b    1         1         1       64m
example-rollout-76f5bddc69   4         4         4       65m

$  kb get pod
NAME                               READY   STATUS    RESTARTS   AGE
example-rollout-66767759b-7rw4j    1/1     Running   0          64m
example-rollout-76f5bddc69-6npjn   1/1     Running   0          65m
example-rollout-76f5bddc69-9pntf   1/1     Running   0          65m
example-rollout-76f5bddc69-bwz6q   1/1     Running   0          65m
example-rollout-76f5bddc69-dqmgb   1/1     Running   0          65m

```

service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-rollout
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
```

```
$ kb apply -f service.yaml
$ minikube service example-rollout
$ curl -s --head 192.168.64.19:31228 | grep Server
Server: nginx/1.15.4
```
