### ISSUE TITLE
Argo Rollouts - Nginx Ingress による Traffic management を試す

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#51]
Argo Rollouts v0.8.2

* https://argoproj.github.io/argo-rollouts/features/traffic-management/nginx/

まずは Argo Rollouts をクラスタレベルにインストールする。

今回は kind を使う。

```
$ kind create cluster --name rollout
$ kubectl create namespace argo-rollouts
$ kubectl apply -n argo-rollouts -f https://raw.githubusercontent.com/argoproj/argo-rollouts/stable/manifests/install.yaml
```

kind に Nginx Ingress Controller をインストールする。

https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx

```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
```

作り方がだめっぽい。

https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster

cluster.yaml

```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

```
$ kind create cluster --name rollout --config cluster.yaml
```
