### ISSUE TITLE
buildflow について書いていく

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#61]
buildflow を導入するために、 buildflow が自分以外の人でも分かる、扱えるものにしないといけない
README はそれなりに書いているが、まだまだ足りない。
一本の大きなブログを書こうと思うとまとまらないので、個々のトピックに関して issue の comment として書いていきたい。
ある程度材料が揃ったらブログにするとか、 README に反映させるのが望ましい。

なぜ buildflow が必要なのか: https://github.com/suzuki-shunsuke/issue/issues/60

**Comment by suzuki-shunsuke** [comment]
# Build, Phase, Task

buildflow には Build, Phase, Task という概念がある。
CircleCI の Pipeline, Workflow, Job みたいなものと思ってもらえるとよい。

```
$ buildflow run
```

で 1 つの build が実行される。
build は複数の phase からなり、 phase が 1 つずつ順に実行される。
phase は複数の task からなり、 task が全て終了すると、その phase も終了となる。
task は並列に実行したり、依存関係を定義したりできる。
task では外部コマンドを実行したりできる。

**Comment by suzuki-shunsuke** [comment]
# task type

task には幾つか type がある。

* command: 外部コマンドを実行
* read_file: 外部ファイルを読み込む
* write_file: テンプレートを指定してファイルを生成

今後他にも type を追加するかもしれない。

**Comment by suzuki-shunsuke** [comment]
# サブコマンド

* init: 設定ファイル .buildflow.yaml がなければ生成する
* run: build を実行する

**Comment by suzuki-shunsuke** [comment]
# 設定ファイルのパス

`buildflow run` を実行したカレントディレクトリからルートディレクトリへと `.buildflow.y[a]ml` を最初にファイルが見つかるまで再帰的に探索します。
`--config (-c)` オプションでパスを指定することも出来ます。

**Comment by suzuki-shunsuke** [comment]
# Hello, world

設定ファイルの雛形を生成します。

```
$ buildflow init
```

これで `buildflow run` を実行すると Hello world が出来てしまいます。

```yaml
$ buildflow run

==============
= Phase: main =
==============
10:47:54UTC | hello | + /bin/sh -c echo hello
10:47:54UTC | hello | 
10:47:54UTC | hello | hello
10:47:54UTC | hello | 

================
= Phase Result: main =
================
status: succeeded
task: hello
status: succeeded
exit code: 0
start time: 2020-10-14T10:47:54Z
end time: 2020-10-14T10:47:54Z
duration: 4.818877ms
+ /bin/sh -c echo hello
hello
```

設定ファイルをみてみましょう。以下ではコメントなどを無視して必要な箇所だけを抜粋することがあります。

```yaml
---
phases:
- name: main
  tasks:
  - name: hello
    command:
      command: echo hello
```

**Comment by suzuki-shunsuke** [comment]
# buildflow の出力

ちょっと出力はわかりにくいかもしれません。
改善したいと思いつつ、どうあるべきなのかまだ見えてないのでこんな感じになっています。

 task の標準出力、標準エラー出力はリアルタイムで出力されます。
また、複数のタスクを並列実行できます。
複数のタスクのログをリアルタイムで出力すると当然混じるので、区別がつくように各行の prefix に `timestamp | task name | ` をつけて出力します。
それでも混じるとわかりにくいので、全 task が完了後に、全 task のログを混ざらないようにそれぞれ標準エラー出力します。

```
==============
= Phase: フェーズ名 =
==============
10:47:54UTC | タスクA | + /bin/sh -c echo hello # 実行されるコマンド
10:47:54UTC | タスクB | + /bin/sh -c echo foo
10:47:54UTC | タスクA | hello # コマンドの標準(エラー)出力
10:47:54UTC | タスクA | 
... # リアルタイムに出力されるので複数の task のログが混ざる場合がある


================
= Phase Result: フェーズ名 = # 該当 phase の全タスク完了後に全タスクの結果と標準(エラー)出力を出力する
================
status: succeeded
task: hello
status: succeeded
exit code: 0
start time: 2020-10-14T10:47:54Z
end time: 2020-10-14T10:47:54Z
duration: 4.818877ms
+ /bin/sh -c echo hello
hello

...
```

**Comment by suzuki-shunsuke** [comment]
# 並列実行

依存関係のない task は並列に実行されます。実行順序は不定です。

設定ファイルの `parallelism` を指定することで最大の並列度を制限できます。デフォルトは無制限です。
例えば `parallelism: 1` とすれば並列で実行されることはなくなります。

**Comment by suzuki-shunsuke** [comment]
# 依存関係の定義

task の dependency を指定することで依存関係を定義できます。将来的に `depends_on` とかにリネームしたりするかもしれません。

```yaml
---
phases:
- name: main
  tasks:
  - name: foo
    command:
      command: |
        sleep 3
        echo foo
  - name: bar
    command:
      command: |
        echo bar
    dependency: # task dependency
    - foo # this task is run after the task foo is finished
```

dependency の指定の仕方は 2 つあります。

- 依存する task の名前のリスト
- 依存する task が全て完了しているか判定する Tengo スクリプト
