### ISSUE TITLE
Lambda を AWS CodeDeploy でデプロイする

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#71]
https://docs.aws.amazon.com/ja_jp/codedeploy/latest/userguide/welcome.html

**Comment by suzuki-shunsuke** [comment]
* Application を作る
* Deployment Group を作る
  * Service Role
  * Deployment Setting
* Applications から Application を選んで Deploy application: https://docs.aws.amazon.com/ja_jp/codedeploy/latest/userguide/deployments-create-console-lambda.html
* AppSpec を用意する
  * https://docs.aws.amazon.com/ja_jp/codedeploy/latest/userguide/application-revisions-appspec-file.html#add-appspec-file-lambda
  * https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html

**Comment by suzuki-shunsuke** [comment]
# AppSpec を使ったデプロイ

```yaml
version: 0.0
Resources:
  - MyFunction: # Replace "MyFunction" with the name of your Lambda function 
      Type: AWS::Lambda::Function
      Properties:
        Name: "test-suzuki-shunsuke" # Specify the name of your Lambda function
        Alias: "develop" # Specify the alias for your Lambda function
        CurrentVersion: "1" # Specify the current version of your Lambda function
        TargetVersion: "2" # Specify the version of your Lambda function to deploy
```

指定した alias の version を Blue/Green Deploy する。
予め function, alias, version は存在する必要がある。

新しい version のリリースは CodeDeploy のカバー範囲ではないように見える。

* create a zip
* update function configuraiton
* update function code
* publish version

ここまでは CodeBuild などの CI ツールでやる感じなのだろうか？

AppSpec を生成し、 deploy をトリガーする必要がある。
