### ISSUE TITLE
cue-lang 入門

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/issue#75]
* https://github.com/cue-lang/cue

Data Validation: https://cuelang.org/docs/usecases/validation/

**Comment by suzuki-shunsuke** [comment]
# cue から YAML を生成

```console
$ cue export --out yaml input.cue
```

**Comment by suzuki-shunsuke** [comment]
## k8s manifest を cue で抽象化したい

まずは deployment を簡単にラップしたい。

```console
$ kubectl create deploy --dry-run=client -o yaml --image=nginx --replicas=3 app > deployment.yaml
```

timestamp とかを消す

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: nginx
        name: nginx
```

cue に変換する

```console
$ cue import deployment.yaml
```

deployment.cue が生成される

```cue
apiVersion: "apps/v1"
kind:       "Deployment"
metadata: {
	labels: app: "app"
	name: "app"
}
spec: {
	replicas: 3
	selector: matchLabels: app: "app"
	template: {
		metadata: labels: app: "app"
		spec: containers: [{
			image: "nginx"
			name:  "nginx"
		}]
	}
}
```

cue から yaml を生成する

```console
$ cue export --out yaml deployment.cue
```

ここから deployment.cue を書き換えていく。
